openapi: 3.0.1
info:
  title: Swagger doc fot test REST API. Backend Xsolla Summer School 2021.
  description: 'RESTful API for e-commerce game developers system which allows to manupulate with product entities.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: gavrilov_k@inbox.ru
externalDocs:
  description: GitHub repository for this project
  url: https://github.com/konstgav/test-api-golang
tags:
- name: Product
  description: All data about products in the store
paths:
  /product/{_id}:
    put:
      tags:
      - product
      summary: Update product
      description: Allow to change properties of a product
      operationId: updateProduct
      parameters:
      - name: _id
        in: path
        description: ID of the product that needs to be updated
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Product object that needs to be updated in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        404:
          description: Product not found
          content: {}
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'  
    get:
      tags:
      - product
      summary: Get the product from store
      operationId: getProduct
      parameters:
      - name: _id
        in: path
        description: ID of the product that need to be read
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      tags:
      - product
      summary: Delete product
      operationId: deleteProduct
      parameters:
      - name: _id
        in: path
        description: ID of the product that needs to be deleted
        required: true
        schema:
          type: integer
          format: int64
      responses:
        404:
          description: Product not found
          content: {}
  /product:
    get:
      tags:
      - product
      summary: Get products
      description: Gets all products using pagination and filtering by product type
      operationId: paginateProducts
      parameters:
      - name: page
        in: path
        description: Page number
        schema:
          type: integer
          format: int64
      - name: limit_per_page
        in: path
        description: Maximum number of products per page
        schema:
          type: integer
          format: int64
      - name: type
        in: path
        description: Type of product
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        404:
          description: Product not found
          content: {}
    post:
      tags:
      - product
      summary: Create product
      description: Creates a new product
      operationId: createNewProduct
      requestBody:
        description: Product object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        404:
          description: Product not found
          content: {}
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: integer
          format: int64
        sku:
          type: string
        name:
          type: string
        type:
          type: string
        price:
          type: integer
          format: int64
      xml:
        name: Product
